### PR TITLE
Added architectural specifications

### PR DESCRIPTION
**Pull request by roireiter**

### CODE REVIEW

**Comment by arielweinstok** [comment]
1. In the test result fragment, i think there should be a separation between what the patient see and what the therapist see.
meaning the patient wont see their result. only the therapist (need to lock the result only to the therapist)

2. "Login of a single patient is allowed to occur on multiple devices at a time." - meaning we allow a single patient to be logged in only on one device at a time? if not, why? ( i saw the next paragraph, not sure it answers my question)

**Comment by roireiter** [comment]
> 

1. How do you suggest we do that? Since I assume the patient and the therapist are using the application at the same time... It can be on the therapist to "take the tablet away" from the patient, and we can show a blocking screen before showing the results. Either way there is no software blocking mechanism for this since there is no "therapist usage" vs "patient usage" of the application - they use it together.
2. - the opposite, meaning we allow a single patient to be logged in **on multiple devices** at a time. Let's say we logged in a patient on one device and he left the test in the middle and the tablet has been lost or broken. We don't wat the patient to be blocked from using the application. The app should deal with the case where the patient is logged in on multiple devices, hence allow such case.

**Comment by arielweinstok** [comment]
1. make a finished test page to show the patient. the therapist will enter the score page after it.
2. i think its a bit problematic. for the case you mentioned we came make a timer for logging out the patient after 30 minutes or something like that. if we allow to enter to a device from multiple devices, there will be more chances of saving the wrong tests in other users profiles.

**Comment by roireiter** [comment]
> 1. make a finished test page to show the patient. the therapist will enter the score page after it.

So this is just a break page with a "Show results" button. OK

> 2. i think its a bit problematic. for the case you mentioned we came make a timer for logging out the patient after 30 minutes or something like that. if we allow to enter to a device from multiple devices, there will be more chances of saving the wrong tests in other users profiles.

If the tablet is lost/broken, or even the less extreme case - the application isn't actively running, there is no way of timing out since the application cannot signal the server of a logout. Maybe there is a possibility of running a background service which I'm unfamiliar with, I'll study on that - but that also means that if the tablet is shut down, we lose the timeout and the patient is locked out. We need to keep in mind that server requests are never guaranteed, and logout may never succeed, if for example there's a poor internet connection.
On the possibility of saving a test for the wrong patient, I think this is a different subject. How is limiting the amount of devices a patient can log into, helping with the case where another patient tries to use a device that's logged in already? We can discuss if the app should logout a patient at certain points to guarantee safety, that's not related to multiple logins of the same patient.

**Comment by arielweinstok** [comment]
OK i get your point.

**Review by arielweinstok — APPROVED** [review]
👍

**Pull request merged**
